### ISSUE TITLE
ControlNet bug: controlnet is enabled but no input image is given

### ISSUE THREAD

**Issue by AugmentedRealityCat** [Trentonom0r3/After-Diffusion#15]
**Describe the bug**
I can generate images but I don't seem to be able to make ControlNet work.

It looks like it cannot find the source layer even though I have selected it in the AESD effect ControlNet parameters.

I tried with and without pre-processor and with different controlNet models as well, but I don't seem to be able to get past that problem.

I also tried with a still picture, a movie and a pre-composited layer as a source for controlNet.

The interface is new to me so this might just be an issue of me not doing the right thing or not doing it in the right order or something similar. I apologize in advance if that is the case.

**Additional context**
log showing what happens whenever I try to use ControlNet. 
```
2023-06-29 23:31:50,449 - ControlNet - WARNING - [canny.processor_res] Invalid value(-1), using default value 512.
2023-06-29 23:31:50,449 - ControlNet - WARNING - [canny.threshold_a] Invalid value(-1), using default value 100.
2023-06-29 23:31:50,450 - ControlNet - WARNING - [canny.threshold_b] Invalid value(-1), using default value 200.
2023-06-29 23:31:50,450 - ControlNet - INFO - Loading model: control_v11p_sd15_canny [d14c016b]
2023-06-29 23:31:50,771 - ControlNet - INFO - Loaded state_dict from [C:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.pth]
2023-06-29 23:31:50,772 - ControlNet - INFO - Loading config: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.yaml
2023-06-29 23:31:52,040 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
*** Error running process: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 739, in process
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
      File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 657, in choose_input_image
        raise ValueError('controlnet is enabled but no input image is given')
    ValueError: controlnet is enabled but no input image is given
```

**Comment by Trentonom0r3** [comment]
> **Describe the bug**
> 
> I can generate images but I don't seem to be able to make ControlNet work.
> 
> 
> 
> It looks like it cannot find the source layer even though I have selected it in the AESD effect ControlNet parameters.
> 
> 
> 
> I tried with and without pre-processor and with different controlNet models as well, but I don't seem to be able to get past that problem.
> 
> 
> 
> I also tried with a still picture, a movie and a pre-composited layer as a source for controlNet.
> 
> 
> 
> The interface is new to me so this might just be an issue of me not doing the right thing or not doing it in the right order or something similar. I apologize in advance if that is the case.
> 
> 
> 
> **Additional context**
> 
> log showing what happens whenever I try to use ControlNet. 
> 
> ```
> 
> 2023-06-29 23:31:50,449 - ControlNet - WARNING - [canny.processor_res] Invalid value(-1), using default value 512.
> 
> 2023-06-29 23:31:50,449 - ControlNet - WARNING - [canny.threshold_a] Invalid value(-1), using default value 100.
> 
> 2023-06-29 23:31:50,450 - ControlNet - WARNING - [canny.threshold_b] Invalid value(-1), using default value 200.
> 
> 2023-06-29 23:31:50,450 - ControlNet - INFO - Loading model: control_v11p_sd15_canny [d14c016b]
> 
> 2023-06-29 23:31:50,771 - ControlNet - INFO - Loaded state_dict from [C:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.pth]
> 
> 2023-06-29 23:31:50,772 - ControlNet - INFO - Loading config: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.yaml
> 
> 2023-06-29 23:31:52,040 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
> 
> *** Error running process: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
> 
>     Traceback (most recent call last):
> 
>       File "C:\stable-diffusion-webui\modules\scripts.py", line 474, in process
> 
>         script.process(p, *script_args)
> 
>       File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 739, in process
> 
>         input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
> 
>       File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 657, in choose_input_image
> 
>         raise ValueError('controlnet is enabled but no input image is given')
> 
>     ValueError: controlnet is enabled but no input image is given
> 
> ```


Ahh, yes! Control image isn't working right now, so you can't use controlnet on Txt2img, you can't use the layer control for input yet, but you can set preprocessor & model and have it run off of your img2img input

> 
> 
> 
>

**Comment by AugmentedRealityCat** [comment]
HA ! I see. I'll try that in a few minutes and I'll close the issue if it's resolved.
Thanks.

**Comment by AugmentedRealityCat** [comment]
That was it ! Thank you so much for the quick answer.
Now back to the magic lesson !
